version: '3'
services:
  zeus:
    build: ./zeus
    container_name: zeus
    command: yarn dev
    restart: always
    volumes:
      - ./zeus:/usr/app
    depends_on:
      - db
    networks:
      - nginx

  thor:
    build: ./thor
    container_name: thor
    command: yarn dev
    restart: always
    volumes:
      - ./thor:/usr/app
    depends_on:
      - db
    networks:
      - nginx

  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zeus
      - thor
    networks:
      - nginx

  db:
    image: postgres:alpine
    restart: always
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=zeus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - nginx

networks: 
  nginx:
    driver: bridge