version: '3'
services:
  zeus:
    build: ./zeus
    container_name: zeus
    command: yarn dev
    restart: always
    # volumes:
    #   - ./zeus:/usr/app
    networks:
      - nginx

  thor:
    build: ./thor
    container_name: thor
    command: yarn dev
    restart: always
    # volumes:
    #   - ./thor:/usr/app
    networks:
      - nginx

  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zeus
      - thor
    networks:
      - nginx


networks: 
  nginx:
    driver: bridge